### ISSUE TITLE
feature: CD add workflows git

### ISSUE THREAD

**Issue by YohanGH** [WildCodeSchool/2409-wns-rouge-ask-and-trust#64]
## Issue Description
Implement Continuous Integration workflows for automatically building and pushing Docker images of both the client and server applications upon code pushes to the staging branch.

## Context
Currently, manual deployments are slowing down development and testing cycles. Automating the build and push process through GitHub Actions workflows ensures faster, more reliable, and consistent updates to staging environments.

## Tasks to Perform
- [ ] add CD
- [ ] add compose.prod.yaml 
  - [ ] remove build add image in compose
- ...

## Expected Result
When changes are pushed to the staging branch, GitHub Actions automatically:

- Logs into Docker Hub.
- Builds Docker images for both client and server applications.
- Pushes the built Docker images tagged as latest to Docker Hub repositories.

## Environment
- [ ] github

## Additional Information

```yml
# .github/workflows/staging-client.yml
name: Compile and push client image

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: ["staging"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # login with Docker
      - uses: docker/login-action@v1
        name: Login to Docker Hub
        with:
          # generate some credentials from Dockerhub and store them into the repo secrets
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      
      # prepare buildx for docker
      - uses: docker/setup-buildx-action@v1
        name: Set up Docker Buildx

      # build an push the newly created image
      - uses: docker/build-push-action@v2
        name: Build and push
        with:
          context: ./client
          file: ./client/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.DOCKER_HUB_CLIENT_IMAGE_NAME }}:latest

```

```yml
# .github/workflows/staging-server.yml
name: Compile and push server image

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: ["staging"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # login with Docker
      - uses: docker/login-action@v1
        name: Login to Docker Hub
        with:
          # generate some credentials from Dockerhub and store them into the repo secrets
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      
      # prepare buildx for docker
      - uses: docker/setup-buildx-action@v1
        name: Set up Docker Buildx

      # build an push the newly created image
      - uses: docker/build-push-action@v2
        name: Build and push
        with:
          context: ./server
          file: ./server/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.DOCKER_HUB_SERVER_IMAGE_NAME }}:latest

```
